### ISSUE TITLE
The openshift template is not working

### ISSUE THREAD

**Issue by jsmadis** [3scale/echo-api#159]
I tried to deploy echo-api on openshift with a given OCP template (https://github.com/3scale/echo-api/blob/master/openshift/echo-api-template.yml), but It failed. 
```

--> Scaling echo-api-1 to 1
--
  | error: update acceptor rejected echo-api-1: pods for rc 'echo-api/echo-api-1' took longer than 180 seconds to become available

```

I am not able to run images from quay.io locally.
```
docker run quay.io/3scale/echoapi:master
docker run quay.io/3scale/echoapi:production
docker run quay.io/3scale/echoapi:latest
```
Any of these commands won't start the container.

I guess that images on quay.io are built incorrectly because I managed to build my own production image and it is working correctly.

Also, I found out that the `v1.0.0` tag is working.

```
docker run quay.io/3scale/echoapi:v1.0.0    
Puma starting in single mode...
* Version 4.3.1 (ruby 2.6.3-p62), codename: Mysterious Traveller
* Min threads: 0, max threads: 16
* Environment: production
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop

```

**Comment by unleashed** [comment]
Hi @jsmadis,

the `master` and `production` tags on quay.io are outdated. We still have not decided what's going to be the policy regarding floating tags. I recommend you use only versioned tags, at least for the time being. We might end up with a v1-stable floating tag at some point meant for deployment.

Regarding the template, it is very much pointing to the outdated tag. Can you try with the `v1.0.0` tag? The template might also need further changes, though.

Ping @maneta @roivaz for feedback / fixes.

**Comment by jsmadis** [comment]
Hi @unleashed,

thank you for your quick response. The template is working with my own echo-api production image.  Also, I tried it with the `v1.0.0` tag which is also working.

**Comment by unleashed** [comment]
#160 should fix this. Thanks!
