### ISSUE TITLE
Only include 'body' if the request body is text

### ISSUE THREAD

**Issue by EricWittmann** [3scale/echo-api#7]
Right now, if you send binary data via e.g. a POST call, the service fails with a stack trace html page.  Check the request body content-type and only include the body if it's a whitelisted content type (application/json, text/*, etc).

**Comment by mikz** [comment]
Steps to reproduce:

```sh
ruby -rnet/http -rsecurerandom -e 'Net::HTTP.new("echo-api.3scale.net").start { |h| p h.post("/foo", SecureRandom.random_bytes(10)) }'
```

**Comment by EricWittmann** [comment]
Yeah, that would probably do it.  :)  

I was testing using Postman and simply added a PNG as the body content for a POST request.

**Comment by msavy** [comment]
It may be related to this? https://github.com/sinatra/sinatra/issues/514

**Comment by msavy** [comment]
It's a rack bug (as mentioned in referenced thread). I'll post a PR for a newer version that fixes it.
