### ISSUE TITLE
Return the request body size and SHA1 hash

### ISSUE THREAD

**Issue by EricWittmann** [3scale/echo-api#8]
Whenever a request has a body (e.g. a PUT or a POST), in addition to including the full body (only when text) in the echo response, also include the size/length of the body as well as the SHA1 hash.

These two properties allow the caller to validate that binary data ( see issue #7 ) was properly sent.

**Comment by msavy** [comment]
> body as well as the SHA1 hash

Is this a convenience thing again or is there some element in this hash that the sender would not know?

That is,  could the sender could calculate the hash themselves by hashing the echoed body?

Just to understand if I'm implementing it as you anticipated. It's not difficult.

> in addition to including the full body (only when text) 

Michal has indicated they used b64 encoding when non-printable data is sent. Do you want the hash over the b64 encoded or raw data (or no preference) in that instance.

**Comment by EricWittmann** [comment]
The goal is to allow the client to quickly verify the data that was sent to the backend.  The primary use-case is for features like outgoing URL re-writing done in an API Gateway.  But also there may be other API Gateway functionality that could modify the request body in some way.  When this is done, the client/test would know what the request body *should* be (after modifications made by the gateway) and thus can validate the body sha1 against an expected sha1.  This is instead of validating the full "body" parameter in the echo service.  I would argue that the "body" parameter is actually no longer useful if the SHA1 hash exists (and results in a smaller response payload).  But obviously we wouldn't want to remove the body param at this point.

**Comment by msavy** [comment]
Agree with what you say.

I can remove the body from the XML output though without affecting the
JSON. Or perhaps something to indicate you don't want it included (API
version or something)

**Comment by EricWittmann** [comment]
That sounds reasonable. :)
