### ISSUE TITLE
The OpenAPI Specification files do not match our current implementation

### ISSUE THREAD

**Issue by nmasse-itix** [3scale/echo-api#80]
Hello,

I noticed a difference between the OpenAPI Specification and our current implementation:

The current spec specifies the `Response` type has a `headers` field which is a list of objects whereas the current implementation returns an object. 

Each individual method specifies the response to be an array of `Response` whereas the current implementation just returns a `Response`.

There might be other differences but this is the ones I noticed.

**Comment by unleashed** [comment]
@thomasmaas can you take a look?

**Comment by unleashed** [comment]
@thomasmaas ping - if you cannot work on this, can you point me to someone I should be bugging before I even think of giving a stab at this?

**Comment by unleashed** [comment]
@thomasmaas pingy!
----------------------------
![Hello, my friend](https://media.giphy.com/media/l4ogV9jeUCeD7uO12W/giphy.gif)

**Comment by unleashed** [comment]
At this stage I think the best course of action is just to dismiss this spec since it is unmaintained. I'll just wait for a few days for any potential feedback here before I hit the big red button.
